# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WellCurve' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # use_frameworks!
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
 
  # Pods for WellCurve

  pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'


  pod 'react-native-maps', :path => '../node_modules/react-native-maps'


  # target 'WellCurveTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

# The following is needed to ensure the "archive" step works in XCode.
# It removes React & Yoga from the Pods project, as it is already included in the main project.
# Without this, you'd see errors when you archive like:
# "Multiple commands produce ... libReact.a"
# "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end
# target 'WellCurve-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for WellCurve-tvOS

#   target 'WellCurve-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
